// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/chat_message.dart';
import 'core/models/course.dart';
import 'core/models/daily_event.dart';
import 'core/models/document_chunk.dart';
import 'core/models/goal.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2306136589620187981),
    name: 'ChatMessage',
    lastPropertyId: const obx_int.IdUid(5, 3430987033585828683),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7602016793102217156),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2822196715898819305),
        name: 'courseId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8903984567527607259),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6265075718109097684),
        name: 'isAi',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3430987033585828683),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8788154451621685830),
    name: 'Course',
    lastPropertyId: const obx_int.IdUid(7, 5600837441044609755),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3664565299404871682),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 790118002500215455),
        name: 'courseId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8009083906631857123),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 811943427154423644),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9197758578622078218),
        name: 'instructor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5380601429053719767),
        name: 'scheduleInfo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2260637861381316690),
        name: 'progressSummary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5600837441044609755),
        name: 'progressPercentage',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1380465176936227641),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(5, 1217631882742256681),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9102544818824723338),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6702694441948999032),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7853137118245848892),
        name: 'sourceDocument',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7837475067166384856),
        name: 'courseId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1217631882742256681),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7344821137094688134),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6282085342872737270),
    name: 'DailyEvent',
    lastPropertyId: const obx_int.IdUid(7, 5513746733200426436),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 171843672486882770),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7685175562242012278),
        name: 'dayOfWeek',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8549675663593421478),
        name: 'startTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1066275384307232071),
        name: 'endTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4032832107243309239),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5565052443035221544),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5513746733200426436),
        name: 'category',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 4402355604015663157),
    name: 'Goal',
    lastPropertyId: const obx_int.IdUid(4, 309848054837852108),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9120528924906030482),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8642932110332666181),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3454100417036715196),
        name: 'progress',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 309848054837852108),
        name: 'statusText',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 4402355604015663157),
    lastIndexId: const obx_int.IdUid(2, 7344821137094688134),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessage: obx_int.EntityDefinition<ChatMessage>(
      model: _entities[0],
      toOneRelations: (ChatMessage object) => [],
      toManyRelations: (ChatMessage object) => {},
      getId: (ChatMessage object) => object.id,
      setId: (ChatMessage object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessage object, fb.Builder fbb) {
        final courseIdOffset = fbb.writeString(object.courseId);
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, courseIdOffset);
        fbb.addOffset(2, textOffset);
        fbb.addBool(3, object.isAi);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final courseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isAiParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = ChatMessage(
          id: idParam,
          courseId: courseIdParam,
          text: textParam,
          isAi: isAiParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    Course: obx_int.EntityDefinition<Course>(
      model: _entities[1],
      toOneRelations: (Course object) => [],
      toManyRelations: (Course object) => {},
      getId: (Course object) => object.id,
      setId: (Course object, int id) {
        object.id = id;
      },
      objectToFB: (Course object, fb.Builder fbb) {
        final courseIdOffset = fbb.writeString(object.courseId);
        final nameOffset = fbb.writeString(object.name);
        final instructorOffset = fbb.writeString(object.instructor);
        final scheduleInfoOffset = fbb.writeString(object.scheduleInfo);
        final progressSummaryOffset = fbb.writeString(object.progressSummary);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, courseIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, instructorOffset);
        fbb.addOffset(4, scheduleInfoOffset);
        fbb.addOffset(5, progressSummaryOffset);
        fbb.addFloat64(6, object.progressPercentage);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final courseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final instructorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final scheduleInfoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final progressSummaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final progressPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = Course(
          id: idParam,
          courseId: courseIdParam,
          name: nameParam,
          instructor: instructorParam,
          scheduleInfo: scheduleInfoParam,
          progressSummary: progressSummaryParam,
          progressPercentage: progressPercentageParam,
        );

        return object;
      },
    ),
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[2],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final sourceDocumentOffset = fbb.writeString(object.sourceDocument);
        final courseIdOffset = fbb.writeString(object.courseId);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, sourceDocumentOffset);
        fbb.addOffset(3, courseIdOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourceDocumentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final courseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = DocumentChunk(
          id: idParam,
          text: textParam,
          sourceDocument: sourceDocumentParam,
          courseId: courseIdParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    DailyEvent: obx_int.EntityDefinition<DailyEvent>(
      model: _entities[3],
      toOneRelations: (DailyEvent object) => [],
      toManyRelations: (DailyEvent object) => {},
      getId: (DailyEvent object) => object.id,
      setId: (DailyEvent object, int id) {
        object.id = id;
      },
      objectToFB: (DailyEvent object, fb.Builder fbb) {
        final dayOfWeekOffset = fbb.writeString(object.dayOfWeek);
        final startTimeOffset = fbb.writeString(object.startTime);
        final endTimeOffset = fbb.writeString(object.endTime);
        final titleOffset = fbb.writeString(object.title);
        final subtitleOffset = fbb.writeString(object.subtitle);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dayOfWeekOffset);
        fbb.addOffset(2, startTimeOffset);
        fbb.addOffset(3, endTimeOffset);
        fbb.addOffset(4, titleOffset);
        fbb.addOffset(5, subtitleOffset);
        fbb.addOffset(6, categoryOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dayOfWeekParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final startTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final endTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final subtitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = DailyEvent(
          id: idParam,
          dayOfWeek: dayOfWeekParam,
          startTime: startTimeParam,
          endTime: endTimeParam,
          title: titleParam,
          subtitle: subtitleParam,
          category: categoryParam,
        );

        return object;
      },
    ),
    Goal: obx_int.EntityDefinition<Goal>(
      model: _entities[4],
      toOneRelations: (Goal object) => [],
      toManyRelations: (Goal object) => {},
      getId: (Goal object) => object.id,
      setId: (Goal object, int id) {
        object.id = id;
      },
      objectToFB: (Goal object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final statusTextOffset = fbb.writeString(object.statusText);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addFloat64(2, object.progress);
        fbb.addOffset(3, statusTextOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final progressParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final statusTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = Goal(
          id: idParam,
          title: titleParam,
          progress: progressParam,
          statusText: statusTextParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessage] entity fields to define ObjectBox queries.
class ChatMessage_ {
  /// See [ChatMessage.id].
  static final id = obx.QueryIntegerProperty<ChatMessage>(
    _entities[0].properties[0],
  );

  /// See [ChatMessage.courseId].
  static final courseId = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[1],
  );

  /// See [ChatMessage.text].
  static final text = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[2],
  );

  /// See [ChatMessage.isAi].
  static final isAi = obx.QueryBooleanProperty<ChatMessage>(
    _entities[0].properties[3],
  );

  /// See [ChatMessage.timestamp].
  static final timestamp = obx.QueryDateProperty<ChatMessage>(
    _entities[0].properties[4],
  );
}

/// [Course] entity fields to define ObjectBox queries.
class Course_ {
  /// See [Course.id].
  static final id = obx.QueryIntegerProperty<Course>(
    _entities[1].properties[0],
  );

  /// See [Course.courseId].
  static final courseId = obx.QueryStringProperty<Course>(
    _entities[1].properties[1],
  );

  /// See [Course.name].
  static final name = obx.QueryStringProperty<Course>(
    _entities[1].properties[2],
  );

  /// See [Course.instructor].
  static final instructor = obx.QueryStringProperty<Course>(
    _entities[1].properties[3],
  );

  /// See [Course.scheduleInfo].
  static final scheduleInfo = obx.QueryStringProperty<Course>(
    _entities[1].properties[4],
  );

  /// See [Course.progressSummary].
  static final progressSummary = obx.QueryStringProperty<Course>(
    _entities[1].properties[5],
  );

  /// See [Course.progressPercentage].
  static final progressPercentage = obx.QueryDoubleProperty<Course>(
    _entities[1].properties[6],
  );
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[2].properties[0],
  );

  /// See [DocumentChunk.text].
  static final text = obx.QueryStringProperty<DocumentChunk>(
    _entities[2].properties[1],
  );

  /// See [DocumentChunk.sourceDocument].
  static final sourceDocument = obx.QueryStringProperty<DocumentChunk>(
    _entities[2].properties[2],
  );

  /// See [DocumentChunk.courseId].
  static final courseId = obx.QueryStringProperty<DocumentChunk>(
    _entities[2].properties[3],
  );

  /// See [DocumentChunk.embedding].
  static final embedding = obx.QueryHnswProperty<DocumentChunk>(
    _entities[2].properties[4],
  );
}

/// [DailyEvent] entity fields to define ObjectBox queries.
class DailyEvent_ {
  /// See [DailyEvent.id].
  static final id = obx.QueryIntegerProperty<DailyEvent>(
    _entities[3].properties[0],
  );

  /// See [DailyEvent.dayOfWeek].
  static final dayOfWeek = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[1],
  );

  /// See [DailyEvent.startTime].
  static final startTime = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[2],
  );

  /// See [DailyEvent.endTime].
  static final endTime = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[3],
  );

  /// See [DailyEvent.title].
  static final title = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[4],
  );

  /// See [DailyEvent.subtitle].
  static final subtitle = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[5],
  );

  /// See [DailyEvent.category].
  static final category = obx.QueryStringProperty<DailyEvent>(
    _entities[3].properties[6],
  );
}

/// [Goal] entity fields to define ObjectBox queries.
class Goal_ {
  /// See [Goal.id].
  static final id = obx.QueryIntegerProperty<Goal>(_entities[4].properties[0]);

  /// See [Goal.title].
  static final title = obx.QueryStringProperty<Goal>(
    _entities[4].properties[1],
  );

  /// See [Goal.progress].
  static final progress = obx.QueryDoubleProperty<Goal>(
    _entities[4].properties[2],
  );

  /// See [Goal.statusText].
  static final statusText = obx.QueryStringProperty<Goal>(
    _entities[4].properties[3],
  );
}
